# Generated by Django 2.1.5 on 2019-02-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_bookinstance_borrow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='status',
        ),
    ]
