# Generated by Django 2.1.5 on 2019-02-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.IntegerField(help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
