# Generated by Django 2.1.5 on 2019-02-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190227_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrow',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='borrow', to='book.Book'),
        ),
    ]
