# Generated by Django 2.1.5 on 2019-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20190227_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
